### ISSUE TITLE
v1.5.1 hangs after `executed` call(but works with 1.4.0)

### ISSUE THREAD

**Issue by subuta** [sheerun/knex-migrate#14]
I have following scripts at `package.json`

```
{
  "scripts": {
     "db:migrate": "knex-migrate up",
     "db:migrate:drop": "knex-migrate down --to 0",
     "db:migrate:reset": "npm run db:migrate:drop && npm run db:migrate"
  }
}
```

When I run `npm run db:migrate:reset` with knex-migrate(v1.5.1), it will hang (looks like waiting for reponse forever?) after this log (of knex with `debug:true` option)

```
{ method: 'pluck',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '794b75ef-f7e5-4600-ac2d-e9224b1bb30a',
  toNative: [Function: toNative],
  sql: 'select "name" from "knex_migrations" order by "id" asc',
  pluck: 'name' }
```

https://github.com/sheerun/knex-migrate/blob/ceefeeda085089158d3737c9625f920028ed18c6/src/storage.js#L69

But when I downgrade knex-migrate `from v1.5.1 to v1.4.0`, It works with same configuration(env) 🤔 

### Postgres logs
I'm not sure is this related...

```
ERROR:  relation "knex_migrations" does not exist at character 25
STATEMENT:  select count("id") from "knex_migrations"
```

#### npm packages
- `knex@0.14.2`
- `knex-migrate@1.5.1`
#### others
- `npm` - `4.2.0`
- `node` - `v7.10.0`
- Uses docker image of `postgres:10-alpine` - `PostgreSQL 10.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.3.0) 6.3.0, 64-bit`

**Comment by rewop** [comment]
I have similar bug. When running commands to migrate/rollback, the process hang. 

Could it be some promises not resolving?

**Comment by sheerun** [comment]
If anyone could help to debug it, I'd be grateful

**Comment by rewop** [comment]
I have the error by just using `v1.5.1` with node `lts/*` (v8.9.4). I add a migration file, and when running the cli `knex-migrate up` the process never exits, however the migration runs. 

Same happens to `down`.

@sheerun can you reproduce with my steps?

**Comment by subuta** [comment]
@sheerun thanks for reply!

> If it still exists, could you modify example project in repository to reproduce this issue?

The error still exists, and reproduced at forked repository by following steps

### Prerequisites

- knex v0.14.2
- knex-migrate v1.5.3
- Use postgres as a db (cannot reproduced with sqlite3)

### Steps to reproduce

1. git clone https://github.com/subuta/knex-migrate
2. npm i && npm run build && cd example npm i // build `package dir` and install dependencies.
3. docker-compose up // to start postgres
4. npm run db:migrate:reset

And it looks like this issue consists with 3 suspicious things.

1. I cannot find exact issue, but `knex v0.14.2` has  some wrong behavior with postgres? 
2. Because old knex-migrate(v1.4.0) had `process.exit(0)` after `main()` resolved, we could ignore `non-resolve promise` issue 😭 (and latest(v1.5.3) version not has `process.exit(0)`)

https://github.com/sheerun/knex-migrate/blob/v1.4.0/src/cli.js#L327
https://github.com/sheerun/knex-migrate/blob/master/src/cli.js#L118

3. These errors might not occur, if you aren't instantiate knex like this way `knex(config.development)` at `knexfile.js` call.

### Conclusion

BTW I can confirm these issues are gone, when I upgrade knex from old version(0.14.2) to `latest version(0.14.4)`. 
So we can close this issue! but it would be nice to add some notice to README or elsewhere 😉 

@sheerun @rewop thanks again for your cooperation!
