### ISSUE TITLE
Provide a way to undo a migration if the migration file can't be found

### ISSUE THREAD

**Issue by carlbennettnz** [sheerun/knex-migrate#15]
Since we started using knex migrations, me and my team all been repeating this – horribly inefficient – workflow:

1) Switch from git branch A to B.
2) Try to start the app. `knex-migrate up` is run as an npm prestart script.
3) `knex-migrate` fails because a migration from branch A can't be found. :angry:
4) Switch back to A.
5) `knex-migrate down` a few times until all of A's migrations have been undone. This often requires looking through git history to figure out which migrations were added before or after B forked.
6) Switch back to B.
7) `npm start` successfully.

It's a bit of a pain.

I can only think of two potential solutions here:

## Git hooks

Some fancy git hook scripts that apply and reverse migrations as you jump from branch to branch. I don't even know if this is possible, but even if it is, this would only solve the problem for my team, not anyone else.

## Storing JavaScript in the database 🙈 

Store the migration file in the `knex_migrations` table, then have `knex-migrate down` eval it to undo each migration. You could even add a command that applies down until it reaches a migration that can be found in the migrations folder, then applies newer migrations. If we ran that command as an npm prestart script, the workflow problem above would go away 😃 

One potential drawback is that bugs in your `down()` become a bit trickier to deal with. This could be mitigated by defaulting to the real file, only using the DB version if it's not found. An error in a `down()` from the database could notify the user that they should checkout the real file first. We could potentially record the git branch and commit they had checked out when they initially applied the migration too.

This also makes the entire concept of migrations a bit harder to understand. Would it be worth it? I don't know. But that's why this is a long issue description, not a PR :smile: What do you think?

**Comment by sheerun** [comment]
Sounds fine and convenient. I'd be up to review and merge if someone submitted such PR.

Implementation probably requires implementing [customResolver](https://github.com/sequelize/umzug#configuration) for umzug that resolves database entries with fallback to local files. As well as changing implementation of [storage](https://github.com/sheerun/knex-migrate/blob/master/src/storage.js) so it returns list of migrations from both database and local filesystem.

Other things to note:
1. It needs to be backward-compatible, so engine should ensure before migration that column storing migration code is present or create **and populate** it otherwise (ensureTable method in engine).
2. Obviously it should also properly handle case when no migration table is present
3. ???

**Comment by sheerun** [comment]
Also the behavior of the command you're imagining is different than both `up` (that is able to run only up migrations) and `down` (that executes only down migrations). It would need to figure out what is the common denominator for code migrations and database migrations, migrate down there, and then migrate upward with all remaining code migrations.

This command would be as dangerous as `knex-migrate down`, so we probably need a `--force` flag if running in production environment (NODE_ENV=production). `knex-migrate up` should be enough for production and is usually harmless, so no `--force` is necessary there.

I guess we could name it `knex-migrate sync` or something.

**Comment by carlbennettnz** [comment]
Sorry I forgot to get back to you on this. After some more thought, I don't think this would be a very good idea.

One major issue I didn't consider when I opened this issue is dependencies. Consider making a new branch, `npm i moment`, then making and applying a new migration that uses moment. Switching back to master, `npm i` to remove moment, then `knex-migrate down` wouldn't work, even with the solution is proposed above.

I'm also using external `.sql` files in my migrations in a few places. These wouldn't be present either.

For those reasons, I'm going to close this for now. Feel free to reopen if you can think of a better solution to the problem.
