### ISSUE TITLE
`pending` and `list` should not fail when no migrations table exists

### ISSUE THREAD

**Issue by chadxz** [sheerun/knex-migrate#17]
Currently, if you run `knex-migrate up` and the corresponding migrations table doesn't exist, it creates the table and performs the migrations.

However, if you run `knex-migrate pending` or `knex-migrate list` with no migrations table, it throws and error stating that the table doesn't exist and exits with an error status.

Ideally, the following would happen when the migrations table doesn't exist:

- `knex-migrate pending` would return no output and exit with a success status
- `knex-migrate list` would return all migrations and exit with a success status

P.S. Thanks for this project it's really a step up from the built-in commands in knex. 🍺

**Comment by chadxz** [comment]
Is this type of change something you'd like implemented? If so I could take a stab at it when time allows.

**Comment by chadxz** [comment]
I've got time to work on this today if it's something you think you'd accept @sheerun

**Comment by sheerun** [comment]
Thank you for wanting to implement this :)

I think following behaviour would be best:
- knex-migrate pending would return all migrations and exit with a success status 
- knex-migrate list would return no output and exit with a success status

So the opposite you've written. If there's no migrations table we should assume all migrations are pending and no migrations were executed.

**Comment by chadxz** [comment]
good ol' opposites. boolean error in my brain lol. Your list is what i intended. Will see about adding that.
