### ISSUE TITLE
Allow a pre-configured knex implementation to be passed to the API

### ISSUE THREAD

**Issue by dmorgantini** [sheerun/knex-migrate#23]
I am trying to use knex-migrate as part of my integration tests.  I will have a manually configured knex instance setup and I'd like to pass it into the knex-migrate, probably something along the lines of: 
```
import knexMigrate from 'knex-migrate';
// init knex somewhere else
const km = knexMigrate(knex);
```
Is this something on your roadmap?  Would a PR help?

**Comment by dmorgantini** [comment]
Ok.  It will be a few weeks as https://github.com/tgriesser/knex/issues/783#issuecomment-216974691 solves my immediate problem.  Any preference for an API?

**Comment by sheerun** [comment]
Implemented as so `knexMigrate({ config: { ... } })`

**Comment by mashaalmemon** [comment]
I'm trying to use the programatic API and pass a knex object in. Based on your last comment this capability is implemented but I don't see any reference to it in the README?

If it is implemented, can other Global options with it:
  --cwd         Specify the working directory
  --migrations  Specify migrations path ($cwd/migrations)
