### ISSUE TITLE
Use typescript (*.ts) file for migrations file

### ISSUE THREAD

**Issue by marcpearson** [sheerun/knex-migrate#25]
knex-migrate force the migrations files pattern to be *.js

Actually, i need to patch knex-migrate index.js to change the pattern to use .ts file

**Comment by sheerun** [comment]
knex-migrate is able to load only .js migrations

**Comment by marcpearson** [comment]
I know but if you change the pattern to match .js or .ts the user can choose which type of migrations file he want to use

Actually, in a project i use typescript migrations with  an aliased command like "node -r ts-node/register ./node_modules/.bin/knex-migrate" but i need to patch the pattern in knex-migrate code

**Comment by sheerun** [comment]
OK, if you really want it you can send PR that makes knex-migrate to accept these, but without any flags.

**Comment by unhawkable** [comment]
@marcpearson also it should include knexfile.ts, if it exists, instead of throwing `No knexfile at '...\knexfile.js'`

**Comment by kylealwyn** [comment]
Would it be possible https://github.com/sheerun/knex-migrate/pull/28 merged in or reviewed if there are issues?

**Comment by sheerun** [comment]
1.7.0 should support this

**Comment by nimish-gupta** [comment]
@sheerun if types are defined in the migration file then it will not work, it will through `SyntaxError`. You have to compile the file into js first if the extension is `ts` and then run the up function.

**Comment by Pencroff** [comment]
> I know but if you change the pattern to match .js or .ts the user can choose which type of migrations file he want to use
> 
> Actually, in a project i use typescript migrations with an aliased command like "node -r ts-node/register ./node_modules/.bin/knex-migrate" but i need to patch the pattern in knex-migrate code

Hi,
Can you help please to understand how do you really use it with typescript?

**Comment by satoyan** [comment]
HI.
I also want to use ES6 features (ex: import) in migration files.
I hope knex cli will support that! :smile:

**Comment by juliancoleman** [comment]
@sheerun `^1.7.2` does not have TypeScript support. Is there any way we might be able to put this into action? `knex` was able to accomplish this by specifying the _"driver"_ (ts-node) internally. I believe that same thing can be accomplished with knex-migrate. This tool is just too useful to not have TypeScript support. Currently, when you try to use a `knexfile.ts`, the following error gets spit out

```bash
$ yarn migrate:rollback   
  yarn run v1.13.0
  $ yarn migrate rollback
  $ knex-migrate --knexfile ./src/config/Knexfile.ts rollback
  Unexpected token {
  error Command failed with exit code 1.
```

**Comment by sheerun** [comment]
Sure I'll accept a PR
