### ISSUE TITLE
Commands fail with "basic" configuration

### ISSUE THREAD

**Issue by maxtruxa** [sheerun/knex-migrate#3]
`knex-migrate` fails to read basic configuations from the knexfile.

This works:
```
module.exports = {
  production: {
    client: '...',
    connection: '...'
  }
};
```

This doesn't:
```
module.exports = {
  client: '...',
  connection: '...'
};
```

Example:
```bash
$ knex-migrate down
Cannot read property 'client' of undefined
```

Basic configurations omitting specific environment blocks (`development`, `staging`, `production`, ...) are supported by knex itself, as shown [in the documentation](http://knexjs.org/#knexfile).

**Comment by sheerun** [comment]
thanks for reporting this

**Comment by davidgwking** [comment]
Cursory scan shows its probably linked to this logic: https://github.com/sheerun/knex-migrate/blob/master/src/cli.js#L80-L84

Is this based on knex's logic for determining whether to use environment-specific configurations?

I'd love to use this library for the fine-grained control over migrations.
