### ISSUE TITLE
knex-migrate: command not found.

### ISSUE THREAD

**Issue by BestInSlot** [sheerun/knex-migrate#30]
running knex: 0.14.6 and knex-migrate: 1.6.1

and I get the following error:
knex-migrate: command not found.

**Comment by sheerun** [comment]
maybe try node_modules/.bin/knex-migrate

**Comment by juan-restrepo** [comment]
I just ran into this and ended up having to install it globally for bash to recognize it
`npm i -g knex-migrate`
Maybe that'll fix it for you
