### ISSUE TITLE
Migration file pattern dosen't match

### ISSUE THREAD

**Issue by ta-kiyama** [sheerun/knex-migrate#31]
When I use `generate` command, Some filename doesn't match.

# example

1. use `knex-migrate generate [hoge]`
1. `YYYYMMDDhhmmss_[hoge].js` is created successflly.
1. use `knex-migrate up`
1. But `YYYYMMDDhhmmss_[hoge].js` doesn't recognize.

# reason

https://github.com/sheerun/knex-migrate/blob/master/src/index.js#L115

This regexp accepts only `[\w-_]+`. So, some filename doesn't match this regexp; e.g. `[` and `]`

knex.js migrations cli supports any filename, so, I want knex-migrate supports it too.

**Comment by sheerun** [comment]
merged pr and released as 1.7.0
