### ISSUE TITLE
Passing config object to knex-migrate('redo') is not parsed.

### ISSUE THREAD

**Issue by loweoj** [sheerun/knex-migrate#42]
I'm trying to run the "redo" command programatically and am passing a config object as follows: 

```
{ config:
   { client: 'mysql',
     connection:
      { host: 'db',
        database: 'dashboard',
        user: ...,
        password: ...,
        port: ... },
     migrations:
      { tableName: 'migrations',
        directory: '/opt/app/src/migrations' } } }
```

This works for `up` and `rollback` commands, but it seems like the code ignores the config "flag" here: https://github.com/sheerun/knex-migrate/blob/master/src/index.js#L294 - my config object never gets passed to `up` and `rollback`.

**Comment by sheerun** [comment]
this is fixed in 1.7.1
