### ISSUE TITLE
Wrong Order of Roll-back Migrations

### ISSUE THREAD

**Issue by mszymulanski** [sheerun/knex-migrate#6]
If a set of migrations is executed within the same second, their roll-back may be executed in a wrong order. 

I have these migrations in my MySql:

| id  | name  | batch  | migration_time  |
|---|---|---|---|
| 39  |  20170406171908_mysql_create_table_status_type.js | 1  | 2017-04-26 21:48:34 |
| 40  | 20170406172149_mysql_init_status_type  | 1  | 2017-04-26 21:48:34  |

In my case, the rollback 1st deletes the table, than tries to de-initialize contents of the deleted table, which results in an error.

`knex-migrate down --to 0` grabs all the migrations, then orders them by the `migration_date`. It should order the migrations by their identifiers. Here is the culprit: 
https://github.com/sheerun/knex-migrate/blob/master/src/storage.js#L59

**Comment by sheerun** [comment]
Thank you for noticing this, I've released a fix, could you check?

**Comment by mszymulanski** [comment]
It resolved the issue. Thank you, @sheerun !
