### ISSUE TITLE
Create Knex Tables Upon the First Up Run

### ISSUE THREAD

**Issue by mszymulanski** [sheerun/knex-migrate#7]
Hi, 
Did you consider having `knex-migrate up` create the knex migration history tables upon the first upward run? The base tool `knex migrate:latest` creates the `knex_migrations` and `knex_migrations_lock` tables if they don't exist. 

Currently `knex-migrate` throws an error if the tables are not present:
     
    `select count(`id`) from `knex_migrations` - Table 'ip_hoarder.knex_migrations' doesn't exist`

**Comment by gaastonsr** [comment]
This should be basic functionality.

**Comment by sheerun** [comment]
I can accept a contribution with this feature. Anyone wants to give a shot?

**Comment by besuhoff** [comment]
@sheerun basically your `tableDoesNotExist` method has stopped working properly. Take a look at #10

**Comment by sheerun** [comment]
@besuhoff Thanks! I've published 1.3.1 could you all check if it works now?

**Comment by besuhoff** [comment]
@sheerun you're very quick at reacting! I've installed 1.3.1 and that worked perfectly for me, thank you. Though I think this place might require some more smart and well-designed fix at some point
